# Generated by Django 3.2.16 on 2023-03-28 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_auto_20230209_1412'),
        ('io_storages', '0012_deeplakeimportstorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepLakeImportStorageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(help_text='External link key', verbose_name='key')),
                ('object_exists', models.BooleanField(default=True, help_text='Whether object under external link still exists', verbose_name='object exists')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation time', verbose_name='created at')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='io_storages.deeplakeimportstorage')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='io_storages_deeplakeimportstoragelink', to='tasks.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
