# Generated by Django 3.2.16 on 2023-04-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('io_storages', '0014_deeplakeexportstorage_deeplakeexportstoragelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deeplakeexportstorage',
            name='source_tensor_name',
        ),
        migrations.AddField(
            model_name='deeplakeexportstorage',
            name='destination_tensor',
            field=models.TextField(blank=True, help_text='Name of the tensor to store the data in', null=True, verbose_name='destination_tensor'),
        ),
        migrations.AddField(
            model_name='deeplakeexportstorage',
            name='source_key',
            field=models.TextField(blank=True, help_text='Key of the source Task JSON', null=True, verbose_name='source_key'),
        ),
        migrations.AddField(
            model_name='deeplakeimportstorage',
            name='server_base_url',
            field=models.TextField(blank=True, help_text='Base URL of the server', null=True, verbose_name='server_base_url'),
        ),
    ]
